INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (1, 'AFG', 93, 'Afghanistan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (2, 'ALB', 355, 'Albania');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (3, 'DZA', 213, 'Algeria');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (4, 'ASM', 684, 'American Samoa');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (5, 'AND', 376, 'Andorra');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (6, 'AGO', 244, 'Angola');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (7, 'AIA', 1264, 'Anguilla');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (8, 'ATA', 672, 'Antarctica');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (9, 'ATG', 1268, 'Antigua And Barbuda');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (10, 'ARG', 54, 'Argentina');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (11, 'ARM', 374, 'Armenia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (12, 'ABW', 297, 'Aruba');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (13, 'AUS', 61, 'Australia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (14, 'AUT', 43, 'Austria');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (15, 'AZE', 994, 'Azerbaijan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (16, 'BHS', 1242, 'Bahamas');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (17, 'BHR', 973, 'Bahrain');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (18, 'BGD', 880, 'Bangladesh');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (19, 'BRB', 1246, 'Barbados');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (20, 'BLR', 375, 'Belarus');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (21, 'BEL', 32, 'Belgium');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (22, 'BLZ', 501, 'Belize');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (23, 'BEN', 229, 'Benin');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (24, 'BMU', 1441, 'Bermuda');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (25, 'BTN', 975, 'Bhutan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (26, 'BOL', 591, 'Bolivia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (27, 'BIH', 387, 'Bosnia And Herzegovina');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (28, 'BWA', 267, 'Botswana');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (29, 'BVT', 0, 'Bouvet Island');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (30, 'BRA', 55, 'Brazil');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (31, 'IOT', 1284, 'British Indian Ocean Territory');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (32, 'BRN', 673, 'Brunei Darussalam');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (33, 'BGR', 359, 'Bulgaria');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (34, 'BFA', 226, 'Burkina Faso');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (35, 'BDI', 257, 'Burundi');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (36, 'KHM', 855, 'Cambodia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (37, 'CMR', 237, 'Cameroon');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (38, 'CAN', 1, 'Canada');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (39, 'CPV', 238, 'Cape Verde');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (40, 'CYM', 1345, 'Cayman Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (41, 'CAF', 236, 'Central African Republic');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (42, 'TCD', 235, 'Chad');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (43, 'CHL', 56, 'Chile');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (44, 'CHN', 86, 'China');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (45, 'CXR', 618, 'Christmas Island');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (46, 'CCK', 61, 'Cocos (Keeling); Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (47, 'COL', 57, 'Colombia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (48, 'COM', 269, 'Comoros');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (49, 'COG', 242, 'Congo');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (50, 'COD', 243, 'Congo, The Democratic Republic Of The');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (51, 'COK', 682, 'Cook Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (52, 'CRI', 506, 'Costa Rica');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (53, 'CIV', 225, 'CÃƒÂ´te d''Ivoire');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (54, 'HRV', 385, 'Croatia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (55, 'CUB', 53, 'Cuba');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (56, 'CYP', 357, 'Cyprus');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (57, 'CZE', 420, 'Czech Republic');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (58, 'DNK', 45, 'Denmark');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (59, 'DJI', 253, 'Djibouti');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (60, 'DMA', 1767, 'Dominica');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (61, 'DOM', 1809, 'Dominican Republic');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (62, 'ECU', 593, 'Ecuador');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (63, 'EGY', 20, 'Egypt');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (64, 'SLV', 503, 'El Salvador');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (65, 'GNQ', 240, 'Equatorial Guinea');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (66, 'ERI', 291, 'Eritrea');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (67, 'EST', 372, 'Estonia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (68, 'ETH', 251, 'Ethiopia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (69, 'FLK', 500, 'Falkland Islands (Malvinas);');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (70, 'FRO', 298, 'Faroe Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (71, 'FJI', 679, 'Fiji');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (72, 'FIN', 358, 'Finland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (73, 'FRA', 33, 'France');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (74, 'GUF', 596, 'French Guiana');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (75, 'PYF', 594, 'French Polynesia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (76, 'ATF', 689, 'French Southern Territories');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (77, 'GAB', 241, 'Gabon');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (78, 'GMB', 220, 'Gambia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (79, 'GEO', 995, 'Georgia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (80, 'DEU', 49, 'Germany');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (81, 'GHA', 233, 'Ghana');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (82, 'GIB', 350, 'Gibraltar');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (83, 'GRC', 30, 'Greece');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (84, 'GRL', 299, 'Greenland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (85, 'GRD', 1473, 'Grenada');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (86, 'GLP', 590, 'Guadeloupe');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (87, 'GUM', 1671, 'Guam');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (88, 'GTM', 502, 'Guatemala');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (89, 'GIN', 224, 'Guinea');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (90, 'GNB', 245, 'Guinea-Bissau');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (91, 'GUY', 592, 'Guyana');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (92, 'HTI', 509, 'Haiti');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (93, 'HMD', 0, 'Heard Island And McDonald Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (94, 'VAT', 0, 'Holy See (Vatican City State);');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (95, 'HND', 504, 'Honduras');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (96, 'HKG', 852, 'Hong Kong');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (97, 'HUN', 36, 'Hungary');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (98, 'ISL', 354, 'Iceland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (99, 'IND', 91, 'India');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (100, 'IDN', 62, 'Indonesia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (101, 'IRN', 98, 'Iran, Islamic Republic Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (102, 'IRQ', 964, 'Iraq');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (103, 'IRL', 353, 'Ireland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (104, 'ISR', 972, 'Israel');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (105, 'ITA', 39, 'Italy');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (106, 'JAM', 1876, 'Jamaica');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (107, 'JPN', 81, 'Japan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (108, 'JOR', 962, 'Jordan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (109, 'KAZ', 7, 'Kazakhstan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (110, 'KEN', 254, 'Kenya');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (111, 'KIR', 686, 'Kiribati');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (112, 'PRK', 850, 'Korea, Democratic People''s Republic Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (113, 'KOR', 82, 'Korea, Republic of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (114, 'KWT', 965, 'Kuwait');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (115, 'KGZ', 996, 'Kyrgyzstan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (116, 'LAO', 856, 'Lao People''s Democratic Republic');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (117, 'LVA', 371, 'Latvia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (118, 'LBN', 961, 'Lebanon');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (119, 'LSO', 266, 'Lesotho');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (120, 'LBR', 231, 'Liberia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (121, 'LBY', 218, 'Libyan Arab Jamahiriya');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (122, 'LIE', 423, 'Liechtenstein');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (123, 'LTU', 370, 'Lithuania');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (124, 'LUX', 352, 'Luxembourg');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (125, 'MAC', 853, 'Macao');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (126, 'MKD', 389, 'Macedonia, The Former Yugoslav Republic Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (127, 'MDG', 261, 'Madagascar');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (128, 'MWI', 265, 'Malawi');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (129, 'MYS', 60, 'Malaysia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (130, 'MDV', 960, 'Maldives');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (131, 'MLI', 223, 'Mali');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (132, 'MLT', 356, 'Malta');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (133, 'MHL', 692, 'Marshall islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (134, 'MTQ', 596, 'Martinique');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (135, 'MRT', 222, 'Mauritania');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (136, 'MUS', 230, 'Mauritius');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (137, 'MYT', 269, 'Mayotte');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (138, 'MEX', 52, 'Mexico');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (139, 'FSM', 691, 'Micronesia, Federated States Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (140, 'MDA', 1808, 'Moldova, Republic Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (141, 'MCO', 377, 'Monaco');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (142, 'MNG', 976, 'Mongolia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (143, 'MSR', 1664, 'Montserrat');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (144, 'MAR', 212, 'Morocco');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (145, 'MOZ', 258, 'Mozambique');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (146, 'MMR', 95, 'Myanmar');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (147, 'NAM', 264, 'Namibia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (148, 'NRU', 674, 'Nauru');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (149, 'NPL', 977, 'Nepal');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (150, 'NLD', 31, 'Netherlands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (151, 'ANT', 599, 'Netherlands Antilles');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (152, 'NCL', 687, 'New Caledonia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (153, 'NZL', 64, 'New Zealand');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (154, 'NIC', 505, 'Nicaragua');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (155, 'NER', 227, 'Niger');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (156, 'NGA', 234, 'Nigeria');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (157, 'NIU', 683, 'Niue');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (158, 'NFK', 672, 'Norfolk Island');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (159, 'MNP', 1670, 'Northern Mariana Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (160, 'NOR', 47, 'Norway');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (161, 'OMN', 968, 'Oman');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (162, 'PAK', 92, 'Pakistan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (163, 'PLW', 680, 'Palau');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (164, 'PSE', 970, 'Palestinian Territory, Occupied');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (165, 'PAN', 507, 'Panama');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (166, 'PNG', 675, 'Papua New Guinea');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (167, 'PRY', 595, 'Paraguay');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (168, 'PER', 51, 'Peru');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (169, 'PHL', 63, 'Philippines');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (170, 'PCN', 0, 'Pitcairn');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (171, 'POL', 48, 'Poland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (172, 'PRT', 351, 'Portugal');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (173, 'PRI', 1787, 'Puerto Rico');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (174, 'QAT', 974, 'Qatar');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (175, 'REU', 262, 'Reunion');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (176, 'ROU', 40, 'Romania');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (177, 'RUS', 7, 'Russian Federation');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (178, 'RWA', 250, 'Rwanda');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (179, 'SHN', 290, 'SaINT Helena');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (180, 'KNA', 1869, 'SaINT Kitts And Nevis');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (181, 'LCA', 1758, 'SaINT Lucia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (182, 'SPM', 508, 'SaINT Pierre And Miquelon');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (183, 'VCT', 1784, 'SaINT Vincent And The Grenadines');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (184, 'WSM', 685, 'Samoa');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (185, 'SMR', 378, 'San Marino');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (186, 'STP', 239, 'SÃƒÂ£o TomÃƒÂ© And Principe');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (187, 'SAU', 966, 'Saudi Arabia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (188, 'SEN', 221, 'Senegal');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (189, 'SYC', 248, 'Seychelles');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (190, 'SLE', 232, 'Sierra Leone');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (191, 'SGP', 65, 'Singapore');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (192, 'SVK', 421, 'Slovakia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (193, 'SVN', 386, 'Slovenia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (194, 'SLB', 677, 'Solomon Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (195, 'SOM', 252, 'Somalia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (196, 'ZAF', 27, 'South Africa');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (197, 'SGS', 0, 'South Georgia And The South Sandwich Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (198, 'ESP', 34, 'Spain');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (199, 'LKA', 94, 'Sri Lanka');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (200, 'SDN', 249, 'Sudan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (201, 'SUR', 597, 'Suriname');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (202, 'SJM', 0, 'Svalbard and Jan Mayen');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (203, 'SWZ', 268, 'Swaziland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (204, 'SWE', 46, 'Sweden');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (205, 'CHE', 41, 'Switzerland');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (206, 'SYR', 963, 'Syrian Arab Republic');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (207, 'TWN', 886, 'Taiwan, Province Of China');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (208, 'TJK', 992, 'Tajikistan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (209, 'TZA', 255, 'Tanzania, United Republic Of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (210, 'THA', 66, 'Thailand');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (211, 'TLS', 670, 'Timor-Leste');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (212, 'TGO', 228, 'Togo');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (213, 'TKL', 690, 'Tokelau');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (214, 'TON', 676, 'Tonga');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (215, 'TTO', 1868, 'Trinidad And Tobago');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (216, 'TUN', 216, 'Tunisia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (217, 'TUR', 90, 'Turkey');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (218, 'TKM', 993, 'Turkmenistan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (219, 'TCA', 1649, 'Turks And Caicos Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (220, 'TUV', 688, 'Tuvalu');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (221, 'UGA', 256, 'Uganda');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (222, 'UKR', 380, 'Ukraine');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (223, 'ARE', 971, 'United Arab Emirates');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (224, 'GBR', 44, 'United Kingdom');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (225, 'USA', 1, 'United States');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (226, 'UMI', 0, 'United States Minor Outlying Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (227, 'URY', 598, 'Uruguay');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (228, 'UZB', 998, 'Uzbekistan');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (229, 'VUT', 678, 'Vanuatu');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (230, 'VEN', 58, 'Venezuela');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (231, 'VNM', 84, 'Vietnam');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (232, 'VGB', 1284, 'Virgin Islands, British');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (233, 'VIR', 808, 'Virgin Islands, U.S.');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (234, 'WLF', 681, 'Wallis And Futuna');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (235, 'ESH', 0, 'Western Sahara');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (236, 'YEM', 967, 'Yemen');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (237, 'YUG', 0, 'Yugoslavia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (238, 'ZMB', 260, 'Zambia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (239, 'ZWE', 263, 'Zimbabwe');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (240, 'ASC', 0, 'Ascension Island');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (241, 'DGA', 0, 'Diego Garcia');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (242, 'XNM', 0, 'Inmarsat');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (243, 'TMP', 0, 'East timor');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (244, 'AK', 0, 'Alaska');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (245, 'HI', 0, 'Hawaii');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (246, 'ALA', 35818, 'Aland Islands');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (247, 'BLM', 0, 'Saint Barthelemy');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (248, 'GGY', 441481, 'Guernsey');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (249, 'IMN', 441624, 'Isle of Man');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (250, 'JEY', 441534, 'Jersey');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (251, 'MAF', 0, 'Saint Martin');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (252, 'MNE', 382, 'Montenegro, Republic of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (253, 'SRB', 381, 'Serbia, Republic of');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (254, 'CPT', 0, 'Clipperton Island');
INSERT INTO `simu_country` (`id`, `countrycode`, `countryprefix`, `countryname`) VALUES (255, 'TAA', 0, 'Tristan da Cunha');
